-- MySQL Script generated by MySQL Workbench
-- ‫سه‌شنبه ۰۷ ژوئن ۱۶، ۱۵:۱۳:۰۵‬
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PhpSite1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PhpSite1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PhpSite1` DEFAULT CHARACTER SET utf8 ;
USE `PhpSite1` ;

-- -----------------------------------------------------
-- Table `Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project` (
  `Project_id` INT NOT NULL AUTO_INCREMENT,
  `register number` VARCHAR(45) NULL,
  `owner` VARCHAR(45) NULL,
  `karfarm_id` VARCHAR(45) NOT NULL,
  `consultant_id` VARCHAR(45) NOT NULL,
  `sabt_no` VARCHAR(45) NULL,
  `sohbat_id` VARCHAR(45) NULL,
  `SahebFile_id` VARCHAR(45) NULL,
  `Projectcol` VARCHAR(45) NULL,
  `pish_factor` TINYINT(1) NULL,
  `pre_congra` TINYINT(1) NULL,
  `register_time` DATETIME NULL,
  PRIMARY KEY (`Project_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Request` (
  `req_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `requester` INT NULL,
  `Time_req` DATETIME NULL,
  `owner` VARCHAR(45) NULL,
  `Project_id` INT NULL,
  `file_path` VARCHAR(200) NULL,
  `Requestcol` VARCHAR(45) NULL,
  `direct_boss` VARCHAR(45) NULL,
  `main_boss` VARCHAR(45) NULL,
  `direct_status` VARCHAR(45) NULL,
  `main_status` VARCHAR(45) NULL,
  `req_time` VARCHAR(45) NULL,
  `ack_direc_time` VARCHAR(45) NULL,
  `ack_main_time` VARCHAR(45) NULL,
  `owner` VARCHAR(45) NULL,
  PRIMARY KEY (`req_id`),
  INDEX `project_id_idx` (`Project_id` ASC),
  CONSTRAINT `project_id`
    FOREIGN KEY (`Project_id`)
    REFERENCES `Project` (`Project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `User` (
  `User_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `pass` CHAR(40) NOT NULL,
  `email` VARCHAR(45) NULL,
  `Adress` VARCHAR(200) NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Family` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `Idcard_number` BIGINT(100) NOT NULL,
  `user_type` INT NOT NULL,
  `shenasname_no` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `enroll_date` DATE NULL,
  `grade` VARCHAR(45) NULL,
  PRIMARY KEY (`User_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `project_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `family` VARCHAR(45) NOT NULL,
  `customer_type` VARCHAR(45) NULL,
  `Tel_no` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_type` (
  `type_id` INT NOT NULL,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
